In [21]:
import pandas as pd
import numpy as np

In [22]:
path_to_scraped_dataset = "../../public/Dino Datasets Scraped.csv"
full_df = pd.read_csv(path_to_scraped_dataset, sep=';')
full_df

,name,diet,period,lived_in,type,bipedal,length,weight,taxonomy,named_by,species,link,Story,dentition,taxonomy_suborder,taxonomy_family
0,tyrannosaurus,carnivorous,Late Cretaceous 68-66 million years ago,USA,large theropod,Yes,12.0m,7000kg,Dinosauria Saurischia Theropoda Neotheropoda T...,Osborn (1905),rex,https://www.nhm.ac.uk/discover/dino-directory/...,Tyrannosaurus lives up to its reputation as on...,"60 saw-edged, bone-crushing, pointed teeth",Saurischia,Tyrannosaurinae
1,allosaurus,carnivorous,Late Jurassic 156-144 million years ago,USA,large theropod,Yes,12.0m,2000kg,Dinosauria Saurischia Theropoda Neotheropoda T...,Marsh (1877),fragilis,https://www.nhm.ac.uk/discover/dino-directory/...,NaN,dagger-like with serrated edges,Saurischia,Allosauridae
2,velociraptor,carnivorous,Late Cretaceous 74-70 million years ago,Mongolia,small theropod,Yes,1.8m,7kg,Dinosauria Saurischia Theropoda Neotheropoda T...,Osborn (1924),mongoliensis,https://www.nhm.ac.uk/discover/dino-directory/...,NaN,"lots of sharp, pointed teeth",Saurischia,Dromaeosauridae
3,spinosaurus,carnivorous,Late Cretaceous 95-70 million years ago,Morocco,large theropod,Yes,18.0m,7400kg,Dinosauria Saurischia Theropoda Neotheropoda T...,Stromer (1915),aegyptiacus,https://www.nhm.ac.uk/discover/dino-directory/...,Spinosaurus was a large meat-eating dinosaur f...,smooth and cone-shaped,Saurischia,Spinosaurinae
4,carnotaurus,carnivorous,Late Cretaceous 70 million years ago,Argentina,large theropod,Yes,7.6m,1 600kg,Dinosauria Saurischia Theropoda Neotheropoda C...,Bonaparte (1985),sastrei,https://www.nhm.ac.uk/discover/dino-directory/...,Carnotaurus was a meat-eating dinosaur with tw...,NaN,Saurischia,Abelisauridae
5,giganotosaurus,carnivorous,Early Cretaceous 112-90 million years ago,Argentina,large theropod,Yes,12.5m,8000kg,Dinosauria Saurischia Theropoda Neotheropoda T...,Coria and Salgado (1995),carolinii,https://www.nhm.ac.uk/discover/dino-directory/...,Giganotosaurus is known from very fragmentary ...,"long, blade-like and serrated - ideal for slicing",Saurischia,Carcharodontosauridae
6,ceratosaurus,carnivorous,Late Jurassic 153-148 million years ago,USA,large theropod,Yes,6.0m,970kg,Dinosauria Saurischia Theropoda Neotheropoda C...,Marsh (1884),nasicornis,https://www.nhm.ac.uk/discover/dino-directory/...,Ceratosaurus was one of the biggest hunters in...,NaN,Saurischia,Neoceratosauria
7,megalosaurus,carnivorous,Mid Jurassic 170-155 million years ago,United Kingdom,large theropod,Yes,9.0m,700kg,Dinosauria Saurischia Theropoda Neotheropoda T...,Ritgen (1826),bucklandii,https://www.nhm.ac.uk/discover/dino-directory/...,"Megalosaurus was a large, meat-eating dinosaur...",NaN,Saurischia,Megalosaurinae
8,compsognathus,carnivorous,Late Jurassic 145-140 million years ago,Germany,small theropod,Yes,0.65m,3kg,Dinosauria Saurischia Theropoda Neotheropoda T...,Wagner (1859),longipes,https://www.nhm.ac.uk/discover/dino-directory/...,NaN,sharp,Saurischia,Compsognathidae
9,dilophosaurus,carnivorous,Early Jurassic 190 million years ago,USA,large theropod,Yes,6.0m,400kg,Dinosauria Saurischia Theropoda Neotheropoda D...,wetherilli,NaN,https://www.nhm.ac.uk/discover/dino-directory/...,Dilophosaurus was a meat-eating dinosaur that ...,lots of sharp and curved teeth,Saurischia,Dilophosauridae
10,baryonyx,carnivorous,Early Cretaceous 125 million years ago,United Kingdom,large theropod,Yes,10.0m,2000kg,Dinosauria Saurischia Theropoda Neotheropoda T...,Charig and Milner (1987),walkeri,https://www.nhm.ac.uk/discover/dino-directory/...,The mouth shape of this dinosaur was very simi...,"sharp, finely serrated teeth",Saurischia,Baryonychinae
11,utahraptor,carnivorous,Early Cretaceous 112-100 million years ago,USA,large theropod,Yes,6.0m,350kg,Dinosauria Saurischia Theropoda Neotheropoda T...,Kirkland Gaston and Burge (1993),ostrommaysorum,https://www.nhm.ac.uk/discover/dino-directory/...,Utahraptor was a meat-eating dinosaur that liv...,"lots of sharp, pointed teeth",Saurischia,Dromaeosauridae
12,deinonychus,carnivorous,Early Cretaceous 120-110 million years ago,USA,small theropod,Yes,3.0m,13.0m,Dinosauria Saurischia Theropoda Neotheropoda T...,Ostrom (1969),antirrhopus,https://www.nhm.ac.uk/discover/dino-directory/...,Deinonychus was a small meat-eating dinosaur. ...,backward-curving,Saurischia,Dromaeosauridae
13,mapusaurus,carnivorous,Late Cretaceous 99-94 million years ago,Argentina,large theropod,Yes,13.0m,3000kg,Dinosauria Saurischia Theropoda Neotheropoda T...,Coria and Currie (2006),roseae,https://www.nhm.ac.uk/discover/dino-directory/...,This dinosaur may have hunted in packs and liv...,NaN,Saurischia,Giganotosaurinae
14,albertosaurus,carnivorous,Late Cretaceous 76-74 million years ago,Canada,large theropod,Yes,9.0m,1500kg,Dinosauria Saurischia Theropoda Neotheropoda T...,Lamb (1914),libratus,https://www.nhm.ac.uk/discover/dino-directory/...,Albertosaurus was a close relative of Tyrannos...,"saw-edged, flesh-slicing teeth",Saurischia,Albertosaurinae
15,dromaeosaurus,carnivorous,Late Cretaceous 76-74 million years ago,USA,small theropod,Yes,1.8m,15kg,Dinosauria Saurischia Theropoda Neotheropoda T...,Matthew and Brown (1922),albertensis,https://www.nhm.ac.uk/discover/dino-directory/...,The back foot of this dinosaur had a large cla...,"small, razor-sharp, backward-curving teeth",Saurischia,Dromaeosauridae
16,acrocanthosaurus,carnivorous,Early Cretaceous 115-105 million years ago,USA,large theropod,Yes,12.0m,6600kg,Dinosauria Saurischia Theropoda Neotheropoda T...,Stovall and Langston (1950),atokensis,https://www.nhm.ac.uk/discover/dino-directory/...,NaN,NaN,Saurischia,Carcharodontosauridae
17,tarbosaurus,carnivorous,Late Cretaceous 74-70 million years ago,Mongolia,large theropod,Yes,10.0m,5000kg,Dinosauria Saurischia Theropoda Neotheropoda T...,Maleev (1955),bataar,https://www.nhm.ac.uk/discover/dino-directory/...,Tarbosaurus is very like Tyrannosaurus.,NaN,Saurischia,Tyrannosaurinae
18,herrerasaurus,carnivorous,Late Triassic 228 million years ago,Argentina,small theropod,Yes,3.0m,350kg,Dinosauria Saurischia Theropoda Herrerasauridae,Reig (1963),ischigualastensis,https://www.nhm.ac.uk/discover/dino-directory/...,NaN,NaN,Saurischia,Herrerasauridae
19,carcharodontosaurus,carnivorous,Late Cretaceous 98-94 million years ago,North Africa,large theropod,Yes,15.0m,6200kg,Dinosauria Saurischia Theropoda Neotheropoda T...,Stromer (1931),saharicus,https://www.nhm.ac.uk/discover/dino-directory/...,Carcharodontosaurus was a very large meat-eati...,NaN,Saurischia,Carcharodontosauridae
20,triceratops,herbivorous,Late Cretaceous 68-66 million years ago,USA,ceratopsian,No,9.0m,5500kg,Dinosauria Ornithischia Genasauria Cerapoda Ma...,Marsh (1889),horridus,https://www.nhm.ac.uk/discover/dino-directory/...,"With its 3 horns, a parrot-like beak and a lar...",horny beak and shearing teeth,Ornithischia,Chasmosaurinae
21,brachiosaurus,herbivorous,Late Jurassic 155-140 million years ago,USA,sauropod,No,30.0m,50000kg,Dinosauria Saurischia Sauropodomorpha Sauropod...,Riggs (1903),altithorax,https://www.nhm.ac.uk/discover/dino-directory/...,Brachiosaurus held its head very high. It is l...,NaN,Saurischia,Brachiosauridae
22,stegosaurus,herbivorous,Late Jurassic 155-145 million years ago,USA,armoured dinosaur,No,9.0m,3000kg,Dinosauria Ornithischia Genasauria Thyreophora...,Marsh (1877),armatus,https://www.nhm.ac.uk/discover/dino-directory/...,"A large, slow moving plant-eater, Stegosaurus ...",NaN,Ornithischia,Stegosaurinae
23,ankylosaurus,herbivorous,Late Cretaceous 74-67 million years ago,USA,armoured dinosaur,No,7.0m,8000kg,Dinosauria Ornithischia Genasauria Thyreophora...,Brown (1908),magniventris,https://www.nhm.ac.uk/discover/dino-directory/...,Ankylosaurus lived during the Late Cretaceous ...,grinding teeth with a beak at the front,Ornithischia,Ankylosauridae
24,diplodocus,herbivorous,Late Jurassic 155-145 million years ago,USA,sauropod,No,26.0m,15000kg,Dinosauria Saurischia Sauropodomorpha Sauropod...,Marsh (1878),longus,https://www.nhm.ac.uk/discover/dino-directory/...,Diplodocus had a long neck that it would have ...,in rows like a comb,Saurischia,Diplodocidae
25,apatosaurus,herbivorous,Late Jurassic 154-145 million years ago,USA,sauropod,No,21.0m,218000kg,Dinosauria Saurischia Sauropodomorpha Sauropod...,Marsh (1877),ajax,https://www.nhm.ac.uk/discover/dino-directory/...,Apatosaurus was a large sauropod dinosaur. It ...,NaN,Saurischia,Diplodocidae
26,iguanodon,herbivorous,Early Cretaceous 140-110 million years ago,United Kingdom,euornithopod,No,10.0m,4000kg,Dinosauria Ornithischia Genasauria Cerapoda Or...,Boulenger and van Beneden (1881),bernissartensis,https://www.nhm.ac.uk/discover/dino-directory/...,Iguanodon could probably walk on all fours or ...,chewing cheek teeth and horny beak,Ornithischia,Iguanodontoidea
27,parasaurolophus,herbivorous,Late Cretaceous 76-74 million years ago,USA,euornithopod,No,11.0m,5000kg,Dinosauria Ornithischia Genasauria Cerapoda Or...,Parks (1922),walkeri,https://www.nhm.ac.uk/discover/dino-directory/...,Parasaurolophus was a duck-billed dinosaur wit...,beak and toothed jaws,Ornithischia,Lambeosaurinae
28,sauropelta,herbivorous,Early Cretaceous 121-94 million years ago,USA,armoured dinosaur,No,6.5m,5000kg,Dinosauria Ornithischia Genasauria Thyreophora...,Ostrom (1970),edwardsorum,https://www.nhm.ac.uk/discover/dino-directory/...,Sauropelta had large shoulder spines.,NaN,Ornithischia,Nodosauridae
29,kentrosaurus,herbivorous,Late Jurassic 155-150 million years ago,Tanzania,armoured dinosaur,No,5.0m,1500kg,Dinosauria Ornithischia Genasauria Thyreophora...,Hennig (1915),aethiopicus,https://www.nhm.ac.uk/discover/dino-directory/...,NaN,NaN,Ornithischia,Stegosaurinae
30,camarasaurus,herbivorous,Late Jurassic 150-140 million years ago,USA,sauropod,No,23.0m,20000kg,Dinosauria Saurischia Sauropodomorpha Sauropod...,Cope (1877),supremus,https://www.nhm.ac.uk/discover/dino-directory/...,Camarasaurus used rows of close-set teeth to s...,"chisel-like, sharp, snipping teeth",Saurischia,Camarasauridae
31,edmontosaurus,herbivorous,Late Cretaceous 76-65 million years ago,Canada,euornithopod,No,13.0m,3400kg,Dinosauria Ornithischia Genasauria Cerapoda Or...,Lambe (1917),regalis,https://www.nhm.ac.uk/discover/dino-directory/...,"Hard conifer needles, twigs and seeeds have be...","horny beak and 1,000 grinding cheek teeth",Ornithischia,Hadrosaurinae
32,corythosaurus,herbivorous,Late Cretaceous 76-74 million years ago,USA,euornithopod,No,10.0m,4000kg,Dinosauria Ornithischia Genasauria Cerapoda Or...,Brown (1914),casuarius,https://www.nhm.ac.uk/discover/dino-directory/...,NaN,NaN,Ornithischia,Lambeosaurinae
33,styracosaurus,herbivorous,Late Cretaceous 76-70 million years ago,USA,ceratopsian,No,5.5m,2700kg,Dinosauria Ornithischia Genasauria Cerapoda Ma...,Lambe (1913),albertensis,https://www.nhm.ac.uk/discover/dino-directory/...,Styracosaurus was a plant-eating dinosaur with...,beak and shearing teeth,Ornithischia,Centrosaurinae
34,plateosaurus,herbivorous,Late Triassic 210 million years ago,Switzerland,sauropod,Yes,7.0m,4000kg,Dinosauria Saurischia Sauropodomorpha Prosauro...,Meyer (1837),engelhardti,https://www.nhm.ac.uk/discover/dino-directory/...,Plateosaurus had 5-fingered hands and a large ...,grinding teeth with a horny beak at the front,Saurischia,Plateosauridae
35,gallimimus,carnivorous,Late Cretaceous 74-70 million years ago,Mongolia,large theropod,Yes,6.0m,200kg,Dinosauria Saurischia Theropoda Neotheropoda T...,Osm√É¬≥lska Roniewicz and Barsbold (1972),bullatus,https://www.nhm.ac.uk/discover/dino-directory/...,Gallimimus was a fast-moving dinosaur that liv...,NaN,Saurischia,Ornithomimidae
36,maiasaura,herbivorous,Late Cretaceous 80-75 million years ago,USA,euornithopod,Yes,9.0m,490kg,Dinosauria Ornithischia Genasauria Cerapoda Or...,Horner and Makela (1979),peeblesorum,https://www.nhm.ac.uk/discover/dino-directory/...,NaN,horny beak and chewing teeth,Ornithischia,Hadrosaurinae
37,lambeosaurus,herbivorous,Late Cretaceous 76-74 million years ago,Canada,euornithopod,Yes,9.0m,2500kg,Dinosauria Ornithischia Genasauria Cerapoda Or...,Parks (1923),lambei,https://www.nhm.ac.uk/discover/dino-directory/...,NaN,NaN,Ornithischia,Lambeosaurinae
38,pachycephalosaurus,herbivorous,Late Cretaceous 76-65 million years ago,USA,euornithopod,Yes,8.0m,450kg,Dinosauria Ornithischia Genasauria Cerapoda Ma...,Brown and Schlaikjer (1943),wyomingensis,https://www.nhm.ac.uk/discover/dino-directory/...,Pachycephalosaurus was an unusual-looking dino...,flat-curved and serrated teeth,Ornithischia,Pachycephalosauridae
39,psittacosaurus,herbivorous,Early Cretaceous 120-100 million years ago,Russia,ceratopsian,Yes,2.0m,50kg,Dinosauria Ornithischia Genasauria Cerapoda Ma...,Osborn (1923),mongoliensis,https://www.nhm.ac.uk/discover/dino-directory/...,NaN,beak,Ornithischia,Psittacosauridae
40,Archaeopteryx,carnivorous,"Late Jurassic,",Germany,small theropod,flies,0.5m,1kg,"Dinosauria, Saurischia, Theropoda, Paraves, Ar...",Mayer (1861),lithographica,https://www.nhm.ac.uk/discover/dino-directory/...,"Archaeopteryx was a small, bird-like dinosaur....","many small, cone-shaped teeth","Saurischia,",Archaeopterygidae
41,Aardonyx,herbivorous,"Early Jurassic,",South Africa,prosauropod,Yes,8.0m,1700kg,"Dinosauria, Saurischia, Sauropodomorpha, Prosa...","Yates, Bonnan, Neveling, Chinsamy and Blackbea...",\ncelestae,https://www.nhm.ac.uk/discover/dino-directory/...,NaN,NaN,"Saurischia,",Anchisauria
42,ammosaurus,herbivorous,Early Jurassic 195-180 million years ago,USA,sauropod,Yes,5.0m,290kg,Dinosauria Saurischia Sauropodomorpha Prosauro...,Marsh (1891),major,https://www.nhm.ac.uk/discover/dino-directory/...,This dinosaur was very similar to Anchisaurus.,NaN,Saurischia,Anchisauridae
43,archaeoceratops,herbivorous,Early Cretaceous 121-99 million years ago,China,ceratopsian,Yes,1.3m,57kg,Dinosauria Ornithischia Genasauria Cerapoda Ma...,Dong and Azuma (1987),oshimai,https://www.nhm.ac.uk/discover/dino-directory/...,NaN,NaN,Ornithischia,Neoceratopsia
44,atlascopcosaurus,herbivorous,Early Cretaceous 121-97 million years ago,Australia,euornithopod,Yes,3.0m,125kg,Dinosauria Ornithischia Genasauria Cerapoda Or...,Rich and Rich (1989),loadsi,https://www.nhm.ac.uk/discover/dino-directory/...,NaN,NaN,Ornithischia,Euornithopoda
45,Agilisaurus,herbivorous,"Late Jurassic,",China,small ornithischian,Yes,1.5m,21kg,"Dinosauria, Ornithischia, Ornithopoda, Euornit...",Peng (1990),NaN,https://www.nhm.ac.uk/discover/dino-directory/...,Agilisaurus is known from a skull and almost c...,NaN,"Ornithischia,",Euornithopoda
46,camptosaurus,herbivorous,Late Jurassic 155-145 million years ago,USA,euornithopod,Yes,5.0m,1000kg,Dinosauria Ornithischia Genasauria Cerapoda Or...,Marsh (1885),dispar,https://www.nhm.ac.uk/discover/dino-directory/...,NaN,beak and grinding teeth,Ornithischia,Ankylopollexia
47,Dracorez,herbivorous,Late Jurassic 155-145 million years ago,USA,pachycephalosaur,Yes,4.0m,100 kg,"Dinosauria, Ornithischia, Neornithischia, Cera...","Bakker, Sullivan, Porter, Larson and Saulsbury...",hogwartsia,https://www.nhm.ac.uk/discover/dino-directory/...,Dracorex is a pachycephalosaur from the end of...,NaN,"Ornithischia,",Pachycephalosauridae
48,Gasparinisaura,herbivorous,Late Cretaceous,Argentina,small ornithopod,Yes,0.8m,13kg,"Dinosauria, Ornithischia, Ornithopoda, Euornit...",Coria and Salgado (1996),cincosaltensis,https://www.nhm.ac.uk/discover/dino-directory/...,NaN,NaN,"Ornithischia,",Euornithopoda
49,Hypsilophodon,herbivorous,Early Cretaceous,UK,small ornithischian,Yes,2.0m,20kg,"Dinosauria, Ornithischia, Neornithischia",Huxley (1869),foxii,https://www.nhm.ac.uk/discover/dino-directory/...,"Hypsilophodon was a small, agile dinosaur that...","turtle-like beak and broad, chisel-like teeth","Ornithischia,",Neornithischia
50,Edmontosaurrus,herbivorous,Late Cretaceous,Canada,large ornithopod,Yes,13.0m,3400kg,"Dinosauria, Ornithischia, Ornithopoda, Hadrosa...",Lambe (1917),regalis,https://www.nhm.ac.uk/discover/dino-directory/...,"Hard conifer needles, twigs and seeeds have be...","horny beak and 1,000 grinding cheek teeth","Ornithischia,",Hadrosaurinae

In [23]:
full_df.columns

Index(['name', 'diet', 'period', 'lived_in', 'type', 'bipedal', 'length',
       'weight', 'taxonomy', 'named_by', 'species', 'link', 'Story',
       'dentition', 'taxonomy_suborder', 'taxonomy_family'],
      dtype='str')

In [24]:
# we drop 'taxonomy', 'link', 'Story', 'dentition',
clean_en_df = full_df[['name', 'diet', 'period', 'lived_in', 'type', 'bipedal', 'length',
       'weight', 'named_by', 'species', 'taxonomy_suborder', 'taxonomy_family']]
clean_en_df

,name,diet,period,lived_in,type,bipedal,length,weight,named_by,species,taxonomy_suborder,taxonomy_family
0,tyrannosaurus,carnivorous,Late Cretaceous 68-66 million years ago,USA,large theropod,Yes,12.0m,7000kg,Osborn (1905),rex,Saurischia,Tyrannosaurinae
1,allosaurus,carnivorous,Late Jurassic 156-144 million years ago,USA,large theropod,Yes,12.0m,2000kg,Marsh (1877),fragilis,Saurischia,Allosauridae
2,velociraptor,carnivorous,Late Cretaceous 74-70 million years ago,Mongolia,small theropod,Yes,1.8m,7kg,Osborn (1924),mongoliensis,Saurischia,Dromaeosauridae
3,spinosaurus,carnivorous,Late Cretaceous 95-70 million years ago,Morocco,large theropod,Yes,18.0m,7400kg,Stromer (1915),aegyptiacus,Saurischia,Spinosaurinae
4,carnotaurus,carnivorous,Late Cretaceous 70 million years ago,Argentina,large theropod,Yes,7.6m,1 600kg,Bonaparte (1985),sastrei,Saurischia,Abelisauridae
5,giganotosaurus,carnivorous,Early Cretaceous 112-90 million years ago,Argentina,large theropod,Yes,12.5m,8000kg,Coria and Salgado (1995),carolinii,Saurischia,Carcharodontosauridae
6,ceratosaurus,carnivorous,Late Jurassic 153-148 million years ago,USA,large theropod,Yes,6.0m,970kg,Marsh (1884),nasicornis,Saurischia,Neoceratosauria
7,megalosaurus,carnivorous,Mid Jurassic 170-155 million years ago,United Kingdom,large theropod,Yes,9.0m,700kg,Ritgen (1826),bucklandii,Saurischia,Megalosaurinae
8,compsognathus,carnivorous,Late Jurassic 145-140 million years ago,Germany,small theropod,Yes,0.65m,3kg,Wagner (1859),longipes,Saurischia,Compsognathidae
9,dilophosaurus,carnivorous,Early Jurassic 190 million years ago,USA,large theropod,Yes,6.0m,400kg,wetherilli,NaN,Saurischia,Dilophosauridae
10,baryonyx,carnivorous,Early Cretaceous 125 million years ago,United Kingdom,large theropod,Yes,10.0m,2000kg,Charig and Milner (1987),walkeri,Saurischia,Baryonychinae
11,utahraptor,carnivorous,Early Cretaceous 112-100 million years ago,USA,large theropod,Yes,6.0m,350kg,Kirkland Gaston and Burge (1993),ostrommaysorum,Saurischia,Dromaeosauridae
12,deinonychus,carnivorous,Early Cretaceous 120-110 million years ago,USA,small theropod,Yes,3.0m,13.0m,Ostrom (1969),antirrhopus,Saurischia,Dromaeosauridae
13,mapusaurus,carnivorous,Late Cretaceous 99-94 million years ago,Argentina,large theropod,Yes,13.0m,3000kg,Coria and Currie (2006),roseae,Saurischia,Giganotosaurinae
14,albertosaurus,carnivorous,Late Cretaceous 76-74 million years ago,Canada,large theropod,Yes,9.0m,1500kg,Lamb (1914),libratus,Saurischia,Albertosaurinae
15,dromaeosaurus,carnivorous,Late Cretaceous 76-74 million years ago,USA,small theropod,Yes,1.8m,15kg,Matthew and Brown (1922),albertensis,Saurischia,Dromaeosauridae
16,acrocanthosaurus,carnivorous,Early Cretaceous 115-105 million years ago,USA,large theropod,Yes,12.0m,6600kg,Stovall and Langston (1950),atokensis,Saurischia,Carcharodontosauridae
17,tarbosaurus,carnivorous,Late Cretaceous 74-70 million years ago,Mongolia,large theropod,Yes,10.0m,5000kg,Maleev (1955),bataar,Saurischia,Tyrannosaurinae
18,herrerasaurus,carnivorous,Late Triassic 228 million years ago,Argentina,small theropod,Yes,3.0m,350kg,Reig (1963),ischigualastensis,Saurischia,Herrerasauridae
19,carcharodontosaurus,carnivorous,Late Cretaceous 98-94 million years ago,North Africa,large theropod,Yes,15.0m,6200kg,Stromer (1931),saharicus,Saurischia,Carcharodontosauridae
20,triceratops,herbivorous,Late Cretaceous 68-66 million years ago,USA,ceratopsian,No,9.0m,5500kg,Marsh (1889),horridus,Ornithischia,Chasmosaurinae
21,brachiosaurus,herbivorous,Late Jurassic 155-140 million years ago,USA,sauropod,No,30.0m,50000kg,Riggs (1903),altithorax,Saurischia,Brachiosauridae
22,stegosaurus,herbivorous,Late Jurassic 155-145 million years ago,USA,armoured dinosaur,No,9.0m,3000kg,Marsh (1877),armatus,Ornithischia,Stegosaurinae
23,ankylosaurus,herbivorous,Late Cretaceous 74-67 million years ago,USA,armoured dinosaur,No,7.0m,8000kg,Brown (1908),magniventris,Ornithischia,Ankylosauridae
24,diplodocus,herbivorous,Late Jurassic 155-145 million years ago,USA,sauropod,No,26.0m,15000kg,Marsh (1878),longus,Saurischia,Diplodocidae
25,apatosaurus,herbivorous,Late Jurassic 154-145 million years ago,USA,sauropod,No,21.0m,218000kg,Marsh (1877),ajax,Saurischia,Diplodocidae
26,iguanodon,herbivorous,Early Cretaceous 140-110 million years ago,United Kingdom,euornithopod,No,10.0m,4000kg,Boulenger and van Beneden (1881),bernissartensis,Ornithischia,Iguanodontoidea
27,parasaurolophus,herbivorous,Late Cretaceous 76-74 million years ago,USA,euornithopod,No,11.0m,5000kg,Parks (1922),walkeri,Ornithischia,Lambeosaurinae
28,sauropelta,herbivorous,Early Cretaceous 121-94 million years ago,USA,armoured dinosaur,No,6.5m,5000kg,Ostrom (1970),edwardsorum,Ornithischia,Nodosauridae
29,kentrosaurus,herbivorous,Late Jurassic 155-150 million years ago,Tanzania,armoured dinosaur,No,5.0m,1500kg,Hennig (1915),aethiopicus,Ornithischia,Stegosaurinae
30,camarasaurus,herbivorous,Late Jurassic 150-140 million years ago,USA,sauropod,No,23.0m,20000kg,Cope (1877),supremus,Saurischia,Camarasauridae
31,edmontosaurus,herbivorous,Late Cretaceous 76-65 million years ago,Canada,euornithopod,No,13.0m,3400kg,Lambe (1917),regalis,Ornithischia,Hadrosaurinae
32,corythosaurus,herbivorous,Late Cretaceous 76-74 million years ago,USA,euornithopod,No,10.0m,4000kg,Brown (1914),casuarius,Ornithischia,Lambeosaurinae
33,styracosaurus,herbivorous,Late Cretaceous 76-70 million years ago,USA,ceratopsian,No,5.5m,2700kg,Lambe (1913),albertensis,Ornithischia,Centrosaurinae
34,plateosaurus,herbivorous,Late Triassic 210 million years ago,Switzerland,sauropod,Yes,7.0m,4000kg,Meyer (1837),engelhardti,Saurischia,Plateosauridae
35,gallimimus,carnivorous,Late Cretaceous 74-70 million years ago,Mongolia,large theropod,Yes,6.0m,200kg,Osm√É¬≥lska Roniewicz and Barsbold (1972),bullatus,Saurischia,Ornithomimidae
36,maiasaura,herbivorous,Late Cretaceous 80-75 million years ago,USA,euornithopod,Yes,9.0m,490kg,Horner and Makela (1979),peeblesorum,Ornithischia,Hadrosaurinae
37,lambeosaurus,herbivorous,Late Cretaceous 76-74 million years ago,Canada,euornithopod,Yes,9.0m,2500kg,Parks (1923),lambei,Ornithischia,Lambeosaurinae
38,pachycephalosaurus,herbivorous,Late Cretaceous 76-65 million years ago,USA,euornithopod,Yes,8.0m,450kg,Brown and Schlaikjer (1943),wyomingensis,Ornithischia,Pachycephalosauridae
39,psittacosaurus,herbivorous,Early Cretaceous 120-100 million years ago,Russia,ceratopsian,Yes,2.0m,50kg,Osborn (1923),mongoliensis,Ornithischia,Psittacosauridae
40,Archaeopteryx,carnivorous,"Late Jurassic,",Germany,small theropod,flies,0.5m,1kg,Mayer (1861),lithographica,"Saurischia,",Archaeopterygidae
41,Aardonyx,herbivorous,"Early Jurassic,",South Africa,prosauropod,Yes,8.0m,1700kg,"Yates, Bonnan, Neveling, Chinsamy and Blackbea...",\ncelestae,"Saurischia,",Anchisauria
42,ammosaurus,herbivorous,Early Jurassic 195-180 million years ago,USA,sauropod,Yes,5.0m,290kg,Marsh (1891),major,Saurischia,Anchisauridae
43,archaeoceratops,herbivorous,Early Cretaceous 121-99 million years ago,China,ceratopsian,Yes,1.3m,57kg,Dong and Azuma (1987),oshimai,Ornithischia,Neoceratopsia
44,atlascopcosaurus,herbivorous,Early Cretaceous 121-97 million years ago,Australia,euornithopod,Yes,3.0m,125kg,Rich and Rich (1989),loadsi,Ornithischia,Euornithopoda
45,Agilisaurus,herbivorous,"Late Jurassic,",China,small ornithischian,Yes,1.5m,21kg,Peng (1990),NaN,"Ornithischia,",Euornithopoda
46,camptosaurus,herbivorous,Late Jurassic 155-145 million years ago,USA,euornithopod,Yes,5.0m,1000kg,Marsh (1885),dispar,Ornithischia,Ankylopollexia
47,Dracorez,herbivorous,Late Jurassic 155-145 million years ago,USA,pachycephalosaur,Yes,4.0m,100 kg,"Bakker, Sullivan, Porter, Larson and Saulsbury...",hogwartsia,"Ornithischia,",Pachycephalosauridae
48,Gasparinisaura,herbivorous,Late Cretaceous,Argentina,small ornithopod,Yes,0.8m,13kg,Coria and Salgado (1996),cincosaltensis,"Ornithischia,",Euornithopoda
49,Hypsilophodon,herbivorous,Early Cretaceous,UK,small ornithischian,Yes,2.0m,20kg,Huxley (1869),foxii,"Ornithischia,",Neornithischia
50,Edmontosaurrus,herbivorous,Late Cretaceous,Canada,large ornithopod,Yes,13.0m,3400kg,Lambe (1917),regalis,"Ornithischia,",Hadrosaurinae

In [25]:
# Translating column names

clean_fr_df = clean_en_df.copy()
column_translation = {
    "name": "nom",
    "diet": "régime_alimentaire",
    "period": "période",
    "lived_in": "habitat",
    "type": "type",
    "bipedal": "bipède",
    "length": "longueur (m)",
    "weight": "poids (kg)",
    "named_by": "nommé_par",
    "species": "espèce",
    "taxonomy_suborder": "sous-ordre_taxonomique",
    "taxonomy_family": "famille_taxonomique"
}
clean_fr_df = clean_fr_df.rename(columns=column_translation)
clean_fr_df.head()

,nom,régime_alimentaire,période,habitat,type,bipède,longueur (m),poids (kg),nommé_par,espèce,sous-ordre_taxonomique,famille_taxonomique
0,tyrannosaurus,carnivorous,Late Cretaceous 68-66 million years ago,USA,large theropod,Yes,12.0m,7000kg,Osborn (1905),rex,Saurischia,Tyrannosaurinae
1,allosaurus,carnivorous,Late Jurassic 156-144 million years ago,USA,large theropod,Yes,12.0m,2000kg,Marsh (1877),fragilis,Saurischia,Allosauridae
2,velociraptor,carnivorous,Late Cretaceous 74-70 million years ago,Mongolia,small theropod,Yes,1.8m,7kg,Osborn (1924),mongoliensis,Saurischia,Dromaeosauridae
3,spinosaurus,carnivorous,Late Cretaceous 95-70 million years ago,Morocco,large theropod,Yes,18.0m,7400kg,Stromer (1915),aegyptiacus,Saurischia,Spinosaurinae
4,carnotaurus,carnivorous,Late Cretaceous 70 million years ago,Argentina,large theropod,Yes,7.6m,1 600kg,Bonaparte (1985),sastrei,Saurischia,Abelisauridae

In [26]:
# Cleaning periods in simpler eras
clean_fr_df["période"] = clean_fr_df["période"].apply(lambda x: ' '.join(x.replace(',', '').split()[:2])) 
clean_fr_df["période"]

0      Late Cretaceous
1        Late Jurassic
2      Late Cretaceous
3      Late Cretaceous
4      Late Cretaceous
5     Early Cretaceous
6        Late Jurassic
7         Mid Jurassic
8        Late Jurassic
9       Early Jurassic
10    Early Cretaceous
11    Early Cretaceous
12    Early Cretaceous
13     Late Cretaceous
14     Late Cretaceous
15     Late Cretaceous
16    Early Cretaceous
17     Late Cretaceous
18       Late Triassic
19     Late Cretaceous
20     Late Cretaceous
21       Late Jurassic
22       Late Jurassic
23     Late Cretaceous
24       Late Jurassic
25       Late Jurassic
26    Early Cretaceous
27     Late Cretaceous
28    Early Cretaceous
29       Late Jurassic
30       Late Jurassic
31     Late Cretaceous
32     Late Cretaceous
33     Late Cretaceous
34       Late Triassic
35     Late Cretaceous
36     Late Cretaceous
37     Late Cretaceous
38     Late Cretaceous
39    Early Cretaceous
40       Late Jurassic
41      Early Jurassic
42      Early Jurassic
43    Early Cretaceous
44    Early Cretaceous
45       Late Jurassic
46       Late Jurassic
47       Late Jurassic
48     Late Cretaceous
49    Early Cretaceous
50     Late Cretaceous
Name: période, dtype: str

In [27]:
# Removing species null values
clean_fr_df = clean_fr_df[~clean_fr_df["espèce"].isnull()]

# Cleaning one weird line where the species starts with a '\n'
bad_index = clean_fr_df[clean_fr_df["espèce"].apply(lambda x:'\n' in x)].index
display(clean_fr_df[clean_fr_df["espèce"].apply(lambda x:'\n' in x)])
print("bad index:", bad_index)
clean_fr_df.loc[bad_index, "espèce"] = clean_fr_df.loc[bad_index, "espèce"].str.replace('\n', '')
clean_fr_df.loc[bad_index, "espèce"]

,nom,régime_alimentaire,période,habitat,type,bipède,longueur (m),poids (kg),nommé_par,espèce,sous-ordre_taxonomique,famille_taxonomique
41,Aardonyx,herbivorous,Early Jurassic,South Africa,prosauropod,Yes,8.0m,1700kg,"Yates, Bonnan, Neveling, Chinsamy and Blackbea...",\ncelestae,"Saurischia,",Anchisauria

bad index: Index([41], dtype='int64')

41    celestae
Name: espèce, dtype: str

In [28]:
# BIG MAPPER
# For each column name we map the translation of all elements
total_mapper = {"régime_alimentaire":  {'carnivorous':'carnivore',
                                        'herbivorous':'herbivore'},
                "période": {
                           "Late Cretaceous": "Crétacé supérieur",
                           "Late Jurassic": "Jurassique supérieur",
                           "Early Cretaceous": "Crétacé inférieur",
                           "Mid Jurassic": "Jurassique moyen",
                           "Early Jurassic": "Jurassique inférieur",
                           "Late Triassic": "Trias supérieur"
                           },
                "habitat": {
                           "USA": "États-Unis",
                           "Mongolia": "Mongolie",
                           "Morocco": "Maroc",
                           "Argentina": "Argentine",
                           "United Kingdom": "Royaume-Uni",
                           "UK": "Royaume-Uni",
                           "Germany": "Allemagne",
                           "Canada": "Canada",
                           "North Africa": "Afrique du Nord",
                           "Tanzania": "Tanzanie",
                           "Switzerland": "Suisse",
                           "Russia": "Russie",
                           "South Africa": "Afrique du Sud",
                           "China": "Chine",
                           "Australia": "Australie"
                           },
                "type": {
                        "large theropod": "grand théropode",
                        "small theropod": "petit théropode",
                        "ceratopsian": "cératopsien",
                        "sauropod": "sauropode",
                        "armoured dinosaur": "dinosaure cuirassé",
                        "euornithopod": "euornithopode",
                        "prosauropod": "prosauropode",
                        "small ornithischian": "petit ornithischien",
                        "pachycephalosaur": "pachycéphalosaure",
                        "small ornithopod": "petit ornithopode",
                        "large ornithopod": "grand ornithopode"
                        },
                "bipède": {
                           "Yes": True,
                           "No": False,
                           "flies": True #only one dino, and it actually has only 2 legs
                        }
}

# And we perform the translation
for key, mapper in total_mapper.items():
    clean_fr_df[key] = clean_fr_df[key].map(mapper).fillna(clean_fr_df[key])

In [29]:
# Capitalize the first letter of the name
clean_fr_df["nom"] = clean_fr_df["nom"].apply(lambda x: x[0].upper() + x[1:])

In [30]:
display(clean_fr_df[clean_fr_df["poids (kg)"].apply(lambda x: x[-1] == "m")])
bad_index = clean_fr_df[clean_fr_df["poids (kg)"].apply(lambda x: x[-1] == "m")].index
display(clean_fr_df.loc[bad_index, "poids (kg)"]) # NOT A WEIGHT
clean_fr_df.loc[bad_index, "poids (kg)"] = "75kg" #source: https://en.wikipedia.org/wiki/Deinonychus#Description
clean_fr_df.loc[bad_index, "poids (kg)"]

,nom,régime_alimentaire,période,habitat,type,bipède,longueur (m),poids (kg),nommé_par,espèce,sous-ordre_taxonomique,famille_taxonomique
12,Deinonychus,carnivore,Crétacé inférieur,États-Unis,petit théropode,True,3.0m,13.0m,Ostrom (1969),antirrhopus,Saurischia,Dromaeosauridae

12    13.0m
Name: poids (kg), dtype: str

12    75kg
Name: poids (kg), dtype: str

In [31]:
# Cleaning longuer and poids to correct format
clean_fr_df["longueur (m)"] = clean_fr_df["longueur (m)"].apply(lambda x: float(x[:-1]))
clean_fr_df["poids (kg)"] = clean_fr_df["poids (kg)"].apply(lambda x: int(x[:-2].replace(' ', '')))

In [32]:
display(clean_fr_df.loc[clean_fr_df["nom"]=="Gallimimus", "nommé_par"])
clean_fr_df.loc[clean_fr_df["nom"]=="Gallimimus", "nommé_par"] = "Osmòlska Roniewicz and Barsbold (1972)"
display(clean_fr_df.loc[clean_fr_df["nom"]=="Gallimimus", "nommé_par"])

35    Osm√É¬≥lska Roniewicz and Barsbold (1972)
Name: nommé_par, dtype: str

35    Osmòlska Roniewicz and Barsbold (1972)
Name: nommé_par, dtype: str

In [33]:
clean_fr_df["sous-ordre_taxonomique"] = clean_fr_df["sous-ordre_taxonomique"].apply(lambda x: x.replace(',', ''))

In [34]:
# TADAAAAA
clean_fr_df

,nom,régime_alimentaire,période,habitat,type,bipède,longueur (m),poids (kg),nommé_par,espèce,sous-ordre_taxonomique,famille_taxonomique
0,Tyrannosaurus,carnivore,Crétacé supérieur,États-Unis,grand théropode,True,12.00,7000,Osborn (1905),rex,Saurischia,Tyrannosaurinae
1,Allosaurus,carnivore,Jurassique supérieur,États-Unis,grand théropode,True,12.00,2000,Marsh (1877),fragilis,Saurischia,Allosauridae
2,Velociraptor,carnivore,Crétacé supérieur,Mongolie,petit théropode,True,1.80,7,Osborn (1924),mongoliensis,Saurischia,Dromaeosauridae
3,Spinosaurus,carnivore,Crétacé supérieur,Maroc,grand théropode,True,18.00,7400,Stromer (1915),aegyptiacus,Saurischia,Spinosaurinae
4,Carnotaurus,carnivore,Crétacé supérieur,Argentine,grand théropode,True,7.60,1600,Bonaparte (1985),sastrei,Saurischia,Abelisauridae
5,Giganotosaurus,carnivore,Crétacé inférieur,Argentine,grand théropode,True,12.50,8000,Coria and Salgado (1995),carolinii,Saurischia,Carcharodontosauridae
6,Ceratosaurus,carnivore,Jurassique supérieur,États-Unis,grand théropode,True,6.00,970,Marsh (1884),nasicornis,Saurischia,Neoceratosauria
7,Megalosaurus,carnivore,Jurassique moyen,Royaume-Uni,grand théropode,True,9.00,700,Ritgen (1826),bucklandii,Saurischia,Megalosaurinae
8,Compsognathus,carnivore,Jurassique supérieur,Allemagne,petit théropode,True,0.65,3,Wagner (1859),longipes,Saurischia,Compsognathidae
10,Baryonyx,carnivore,Crétacé inférieur,Royaume-Uni,grand théropode,True,10.00,2000,Charig and Milner (1987),walkeri,Saurischia,Baryonychinae
11,Utahraptor,carnivore,Crétacé inférieur,États-Unis,grand théropode,True,6.00,350,Kirkland Gaston and Burge (1993),ostrommaysorum,Saurischia,Dromaeosauridae
12,Deinonychus,carnivore,Crétacé inférieur,États-Unis,petit théropode,True,3.00,75,Ostrom (1969),antirrhopus,Saurischia,Dromaeosauridae
13,Mapusaurus,carnivore,Crétacé supérieur,Argentine,grand théropode,True,13.00,3000,Coria and Currie (2006),roseae,Saurischia,Giganotosaurinae
14,Albertosaurus,carnivore,Crétacé supérieur,Canada,grand théropode,True,9.00,1500,Lamb (1914),libratus,Saurischia,Albertosaurinae
15,Dromaeosaurus,carnivore,Crétacé supérieur,États-Unis,petit théropode,True,1.80,15,Matthew and Brown (1922),albertensis,Saurischia,Dromaeosauridae
16,Acrocanthosaurus,carnivore,Crétacé inférieur,États-Unis,grand théropode,True,12.00,6600,Stovall and Langston (1950),atokensis,Saurischia,Carcharodontosauridae
17,Tarbosaurus,carnivore,Crétacé supérieur,Mongolie,grand théropode,True,10.00,5000,Maleev (1955),bataar,Saurischia,Tyrannosaurinae
18,Herrerasaurus,carnivore,Trias supérieur,Argentine,petit théropode,True,3.00,350,Reig (1963),ischigualastensis,Saurischia,Herrerasauridae
19,Carcharodontosaurus,carnivore,Crétacé supérieur,Afrique du Nord,grand théropode,True,15.00,6200,Stromer (1931),saharicus,Saurischia,Carcharodontosauridae
20,Triceratops,herbivore,Crétacé supérieur,États-Unis,cératopsien,False,9.00,5500,Marsh (1889),horridus,Ornithischia,Chasmosaurinae
21,Brachiosaurus,herbivore,Jurassique supérieur,États-Unis,sauropode,False,30.00,50000,Riggs (1903),altithorax,Saurischia,Brachiosauridae
22,Stegosaurus,herbivore,Jurassique supérieur,États-Unis,dinosaure cuirassé,False,9.00,3000,Marsh (1877),armatus,Ornithischia,Stegosaurinae
23,Ankylosaurus,herbivore,Crétacé supérieur,États-Unis,dinosaure cuirassé,False,7.00,8000,Brown (1908),magniventris,Ornithischia,Ankylosauridae
24,Diplodocus,herbivore,Jurassique supérieur,États-Unis,sauropode,False,26.00,15000,Marsh (1878),longus,Saurischia,Diplodocidae
25,Apatosaurus,herbivore,Jurassique supérieur,États-Unis,sauropode,False,21.00,218000,Marsh (1877),ajax,Saurischia,Diplodocidae
26,Iguanodon,herbivore,Crétacé inférieur,Royaume-Uni,euornithopode,False,10.00,4000,Boulenger and van Beneden (1881),bernissartensis,Ornithischia,Iguanodontoidea
27,Parasaurolophus,herbivore,Crétacé supérieur,États-Unis,euornithopode,False,11.00,5000,Parks (1922),walkeri,Ornithischia,Lambeosaurinae
28,Sauropelta,herbivore,Crétacé inférieur,États-Unis,dinosaure cuirassé,False,6.50,5000,Ostrom (1970),edwardsorum,Ornithischia,Nodosauridae
29,Kentrosaurus,herbivore,Jurassique supérieur,Tanzanie,dinosaure cuirassé,False,5.00,1500,Hennig (1915),aethiopicus,Ornithischia,Stegosaurinae
30,Camarasaurus,herbivore,Jurassique supérieur,États-Unis,sauropode,False,23.00,20000,Cope (1877),supremus,Saurischia,Camarasauridae
31,Edmontosaurus,herbivore,Crétacé supérieur,Canada,euornithopode,False,13.00,3400,Lambe (1917),regalis,Ornithischia,Hadrosaurinae
32,Corythosaurus,herbivore,Crétacé supérieur,États-Unis,euornithopode,False,10.00,4000,Brown (1914),casuarius,Ornithischia,Lambeosaurinae
33,Styracosaurus,herbivore,Crétacé supérieur,États-Unis,cératopsien,False,5.50,2700,Lambe (1913),albertensis,Ornithischia,Centrosaurinae
34,Plateosaurus,herbivore,Trias supérieur,Suisse,sauropode,True,7.00,4000,Meyer (1837),engelhardti,Saurischia,Plateosauridae
35,Gallimimus,carnivore,Crétacé supérieur,Mongolie,grand théropode,True,6.00,200,Osmòlska Roniewicz and Barsbold (1972),bullatus,Saurischia,Ornithomimidae
36,Maiasaura,herbivore,Crétacé supérieur,États-Unis,euornithopode,True,9.00,490,Horner and Makela (1979),peeblesorum,Ornithischia,Hadrosaurinae
37,Lambeosaurus,herbivore,Crétacé supérieur,Canada,euornithopode,True,9.00,2500,Parks (1923),lambei,Ornithischia,Lambeosaurinae
38,Pachycephalosaurus,herbivore,Crétacé supérieur,États-Unis,euornithopode,True,8.00,450,Brown and Schlaikjer (1943),wyomingensis,Ornithischia,Pachycephalosauridae
39,Psittacosaurus,herbivore,Crétacé inférieur,Russie,cératopsien,True,2.00,50,Osborn (1923),mongoliensis,Ornithischia,Psittacosauridae
40,Archaeopteryx,carnivore,Jurassique supérieur,Allemagne,petit théropode,True,0.50,1,Mayer (1861),lithographica,Saurischia,Archaeopterygidae
41,Aardonyx,herbivore,Jurassique inférieur,Afrique du Sud,prosauropode,True,8.00,1700,"Yates, Bonnan, Neveling, Chinsamy and Blackbea...",celestae,Saurischia,Anchisauria
42,Ammosaurus,herbivore,Jurassique inférieur,États-Unis,sauropode,True,5.00,290,Marsh (1891),major,Saurischia,Anchisauridae
43,Archaeoceratops,herbivore,Crétacé inférieur,Chine,cératopsien,True,1.30,57,Dong and Azuma (1987),oshimai,Ornithischia,Neoceratopsia
44,Atlascopcosaurus,herbivore,Crétacé inférieur,Australie,euornithopode,True,3.00,125,Rich and Rich (1989),loadsi,Ornithischia,Euornithopoda
46,Camptosaurus,herbivore,Jurassique supérieur,États-Unis,euornithopode,True,5.00,1000,Marsh (1885),dispar,Ornithischia,Ankylopollexia
47,Dracorez,herbivore,Jurassique supérieur,États-Unis,pachycéphalosaure,True,4.00,100,"Bakker, Sullivan, Porter, Larson and Saulsbury...",hogwartsia,Ornithischia,Pachycephalosauridae
48,Gasparinisaura,herbivore,Crétacé supérieur,Argentine,petit ornithopode,True,0.80,13,Coria and Salgado (1996),cincosaltensis,Ornithischia,Euornithopoda
49,Hypsilophodon,herbivore,Crétacé inférieur,Royaume-Uni,petit ornithischien,True,2.00,20,Huxley (1869),foxii,Ornithischia,Neornithischia
50,Edmontosaurrus,herbivore,Crétacé supérieur,Canada,grand ornithopode,True,13.00,3400,Lambe (1917),regalis,Ornithischia,Hadrosaurinae

In [ ]:
# Saving the translated dataset

# Uncomment to overwrite the current file
#clean_fr_df.to_csv("../../public/raw_dino_tables/DinoDatasetFrench.csv", index=False)