In [2]:
import pandas as pd

In [13]:
df = pd.read_json("../experiment-collections/collection_pilot_2026-05-26.jsonl", lines=True)
df

,StartTime,UserIDs,GroupNb,Condition,DLStartTime,DataLabels,DataLabellingNotes,DLEndTime,FSStartTime,SelectedFeatures,...,TrainedTree,BBModellingAnswers,ModelTrainingAccuracyPercent,ModelEndTime,EvalStartTime,AccuracyAttempts,ModelTestingAccuracyPercent,PerfSatisfactionAnswer,ImprovementsAnswer,EvalEndTime
0,2026-05-26T08:27:09.143Z,"[182, 378, 850]",1,C1,2026-05-26T08:27:10.223Z,"{'Apatosaurus': 'herbivore', 'Brachiosaurus': ...",,2026-05-26T08:29:07.793Z,2026-05-26T08:29:07.819Z,"[poids (kg), longueur (m), bipède, période]",...,"{'bipède = faux': {'yes': 'herbivore', 'no': {...",NaN,90,2026-05-26T08:33:47.029Z,2026-05-26T08:33:47.181Z,17,70,bah oui,que se soit plus intuitif et plus simple,2026-05-26T08:44:38.108Z
1,2026-05-26T08:26:40.958Z,"[859, 204, 763]",2,C1,2026-05-26T08:26:42.073Z,"{'Apatosaurus': 'herbivore', 'Brachiosaurus': ...",,2026-05-26T08:32:22.303Z,2026-05-26T08:32:22.329Z,"[poids (kg), longueur (m), famille_taxonomique...",...,"{'poids (kg) ≥ 50000': {'yes': 'herbivore', 'n...",NaN,100,2026-05-26T08:40:23.831Z,2026-05-26T08:40:24.925Z,16,70,je suis satisfait parce que il a eu presque to...,on est la,2026-05-26T08:49:59.874Z
2,2026-05-26T08:26:29.985Z,"[784, 212, 128]",1,C3,2026-05-26T08:26:32.335Z,None,ils se déplacent en groupe. Ses grandes dent q...,2026-05-26T08:43:28.835Z,2026-05-26T08:43:28.868Z,None,...,None,Le modèle agit selon ses propres règles et tu ...,100,2026-05-26T08:50:05.662Z,2026-05-26T08:50:05.841Z,2,30,pas trop car la plus part était faux,je devrait plus détailler,2026-05-26T08:56:55.033Z
3,2026-05-26T08:25:33.465Z,"[689, 316, 577]",2,C3,2026-05-26T08:28:16.037Z,None,,2026-05-26T08:30:29.397Z,2026-05-26T08:30:29.420Z,None,...,None,Le modèle agit selon ses propres règles et tu ...,100,2026-05-26T08:48:58.222Z,2026-05-26T08:48:58.384Z,4,30,non ces nul,jia regarder les juste et les faux,2026-05-26T09:01:40.254Z

In [14]:
df["DLDuration (min)"] = round((pd.to_datetime(df["DLEndTime"]) - pd.to_datetime(df["DLStartTime"])).dt.total_seconds() / 60, 1)
df["FSDuration (min)"] = round((pd.to_datetime(df["FSEndTime"]) - pd.to_datetime(df["FSStartTime"])).dt.total_seconds() / 60, 1)
df["ModelDuration (min)"] = round((pd.to_datetime(df["ModelEndTime"]) - pd.to_datetime(df["ModelStartTime"])).dt.total_seconds() / 60, 1)
df["EvalDuration (min)"] = round((pd.to_datetime(df["EvalEndTime"]) - pd.to_datetime(df["EvalStartTime"])).dt.total_seconds() / 60, 1)

In [15]:
df

,StartTime,UserIDs,GroupNb,Condition,DLStartTime,DataLabels,DataLabellingNotes,DLEndTime,FSStartTime,SelectedFeatures,...,EvalStartTime,AccuracyAttempts,ModelTestingAccuracyPercent,PerfSatisfactionAnswer,ImprovementsAnswer,EvalEndTime,DLDuration (min),FSDuration (min),ModelDuration (min),EvalDuration (min)
0,2026-05-26T08:27:09.143Z,"[182, 378, 850]",1,C1,2026-05-26T08:27:10.223Z,"{'Apatosaurus': 'herbivore', 'Brachiosaurus': ...",,2026-05-26T08:29:07.793Z,2026-05-26T08:29:07.819Z,"[poids (kg), longueur (m), bipède, période]",...,2026-05-26T08:33:47.181Z,17,70,bah oui,que se soit plus intuitif et plus simple,2026-05-26T08:44:38.108Z,2.0,1.4,3.3,10.8
1,2026-05-26T08:26:40.958Z,"[859, 204, 763]",2,C1,2026-05-26T08:26:42.073Z,"{'Apatosaurus': 'herbivore', 'Brachiosaurus': ...",,2026-05-26T08:32:22.303Z,2026-05-26T08:32:22.329Z,"[poids (kg), longueur (m), famille_taxonomique...",...,2026-05-26T08:40:24.925Z,16,70,je suis satisfait parce que il a eu presque to...,on est la,2026-05-26T08:49:59.874Z,5.7,5.9,2.1,9.6
2,2026-05-26T08:26:29.985Z,"[784, 212, 128]",1,C3,2026-05-26T08:26:32.335Z,None,ils se déplacent en groupe. Ses grandes dent q...,2026-05-26T08:43:28.835Z,2026-05-26T08:43:28.868Z,None,...,2026-05-26T08:50:05.841Z,2,30,pas trop car la plus part était faux,je devrait plus détailler,2026-05-26T08:56:55.033Z,16.9,5.3,1.4,6.8
3,2026-05-26T08:25:33.465Z,"[689, 316, 577]",2,C3,2026-05-26T08:28:16.037Z,None,,2026-05-26T08:30:29.397Z,2026-05-26T08:30:29.420Z,None,...,2026-05-26T08:48:58.384Z,4,30,non ces nul,jia regarder les juste et les faux,2026-05-26T09:01:40.254Z,2.2,8.2,10.2,12.7